import jsPDF from "jspdf";

function ExportPDF({ data }) {
  const generatePDF = () => {
    const doc = new jsPDF();

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    const margin = 20;
    const maxWidth = pageWidth - margin * 2;

    let y = 20;

    // Helper for automatic page break
    const checkPage = (spaceNeeded = 10) => {
      if (y + spaceNeeded > pageHeight - 20) {
        doc.addPage();
        y = 20;
      }
    };

    // ========= TITLE =========

    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, pageWidth, 28, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);

    doc.text(
      "AI Investment Research Report",
      pageWidth / 2,
      18,
      { align: "center" }
    );

    y = 40;

    doc.setTextColor(0, 0, 0);

    // ========= COMPANY INFO =========

    doc.setFontSize(17);
    doc.setFont("helvetica", "bold");
    doc.text("Company Information", margin, y);

    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    doc.text(`Company : ${data.company}`, margin, y);

    y += 8;

    doc.text(
      `Recommendation : ${data.analysis.recommendation}`,
      margin,
      y
    );

    y += 8;

    doc.text(
      `Investment Score : ${data.analysis.investmentScore}/100`,
      margin,
      y
    );

    y += 8;

    doc.text(
      `Risk Score : ${data.analysis.riskScore}/100`,
      margin,
      y
    );

    y += 15;

    // ========= AI REASONING =========

    checkPage(40);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("AI Reasoning", margin, y);

    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    const reasoning = doc.splitTextToSize(
      data.analysis.reasoning,
      maxWidth
    );

    reasoning.forEach((line) => {
      checkPage(8);
      doc.text(line, margin, y);
      y += 7;
    });

    y += 8;

    // ========= SWOT =========

    const printSection = (title, items) => {
      checkPage(25);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(15);
      doc.text(title, margin, y);

      y += 8;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);

      items.forEach((item) => {
        const lines = doc.splitTextToSize(item, maxWidth - 8);

        lines.forEach((line, index) => {
          checkPage(8);

          if (index === 0) {
            doc.text("•", margin, y);
            doc.text(line, margin + 8, y);
          } else {
            doc.text(line, margin + 8, y);
          }

          y += 7;
        });

        y += 2;
      });

      y += 5;
    };

    printSection("Strengths", data.analysis.strengths);
    printSection("Weaknesses", data.analysis.weaknesses);
    printSection("Opportunities", data.analysis.opportunities);
    printSection("Threats", data.analysis.threats);

    // ========= FOOTER =========

    const pages = doc.getNumberOfPages();

    for (let i = 1; i <= pages; i++) {
      doc.setPage(i);

      doc.setDrawColor(200);
      doc.line(20, pageHeight - 15, pageWidth - 20, pageHeight - 15);

      doc.setFontSize(10);

      doc.text(
        `Generated by AI Investment Research Agent`,
        margin,
        pageHeight - 8
      );

      doc.text(
        `Page ${i} of ${pages}`,
        pageWidth - 20,
        pageHeight - 8,
        { align: "right" }
      );
    }

    doc.save(`${data.company}-Investment-Report.pdf`);
  };

  return (
    <button
      onClick={generatePDF}
      className="bg-green-600 hover:bg-green-700 text-white px-6 py-3 rounded-lg shadow-lg"
    >
      📄 Download PDF Report
    </button>
  );
}

export default ExportPDF;